name: Push S3 changes

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  push_to_s3:
    name: Push to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          sudo apt update -y;
          sudo apt install terraform -y;
          sudo apt install awscli -y;

      - name: Initialize Terraform and Plan
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}

          terraform init
          terraform plan

      - name: Save terraform tfstate file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add new files via GitHub Actions"
          git push origin HEAD:main

      - name: Apply terraform changes
        run: |
          terraform apply
          
